/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AgentEscrow {
  export type JobStruct = {
    jobId: BytesLike;
    client: AddressLike;
    agent: AddressLike;
    token: AddressLike;
    amount: BigNumberish;
    status: BigNumberish;
    intentHash: string;
    createdAt: BigNumberish;
    completedAt: BigNumberish;
  };

  export type JobStructOutput = [
    jobId: string,
    client: string,
    agent: string,
    token: string,
    amount: bigint,
    status: bigint,
    intentHash: string,
    createdAt: bigint,
    completedAt: bigint
  ] & {
    jobId: string;
    client: string;
    agent: string;
    token: string;
    amount: bigint;
    status: bigint;
    intentHash: string;
    createdAt: bigint;
    completedAt: bigint;
  };
}

export interface AgentEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "completeJob"
      | "createJob"
      | "fundJob"
      | "getJob"
      | "jobIds"
      | "jobs"
      | "owner"
      | "rejectJob"
      | "renounceOwnership"
      | "submitJob"
      | "totalJobs"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "JobCompleted"
      | "JobCreated"
      | "JobFunded"
      | "JobRefunded"
      | "JobRejected"
      | "JobSubmitted"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "completeJob",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createJob",
    values: [BytesLike, AddressLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "fundJob", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "getJob", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "jobIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "jobs", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rejectJob",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitJob",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "totalJobs", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "completeJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fundJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jobIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rejectJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalJobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace JobCompletedEvent {
  export type InputTuple = [jobId: BytesLike, paidAmount: BigNumberish];
  export type OutputTuple = [jobId: string, paidAmount: bigint];
  export interface OutputObject {
    jobId: string;
    paidAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCreatedEvent {
  export type InputTuple = [
    jobId: BytesLike,
    client: AddressLike,
    agent: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    jobId: string,
    client: string,
    agent: string,
    token: string,
    amount: bigint
  ];
  export interface OutputObject {
    jobId: string;
    client: string;
    agent: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobFundedEvent {
  export type InputTuple = [jobId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [jobId: string, amount: bigint];
  export interface OutputObject {
    jobId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobRefundedEvent {
  export type InputTuple = [jobId: BytesLike, refundAmount: BigNumberish];
  export type OutputTuple = [jobId: string, refundAmount: bigint];
  export interface OutputObject {
    jobId: string;
    refundAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobRejectedEvent {
  export type InputTuple = [jobId: BytesLike];
  export type OutputTuple = [jobId: string];
  export interface OutputObject {
    jobId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobSubmittedEvent {
  export type InputTuple = [jobId: BytesLike];
  export type OutputTuple = [jobId: string];
  export interface OutputObject {
    jobId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): AgentEscrow;
  waitForDeployment(): Promise<this>;

  interface: AgentEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  completeJob: TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;

  createJob: TypedContractMethod<
    [
      jobId: BytesLike,
      agent: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      intentHash: string
    ],
    [void],
    "nonpayable"
  >;

  fundJob: TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;

  getJob: TypedContractMethod<
    [jobId: BytesLike],
    [AgentEscrow.JobStructOutput],
    "view"
  >;

  jobIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  jobs: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        jobId: string;
        client: string;
        agent: string;
        token: string;
        amount: bigint;
        status: bigint;
        intentHash: string;
        createdAt: bigint;
        completedAt: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  rejectJob: TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  submitJob: TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;

  totalJobs: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "completeJob"
  ): TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createJob"
  ): TypedContractMethod<
    [
      jobId: BytesLike,
      agent: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      intentHash: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundJob"
  ): TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<
    [jobId: BytesLike],
    [AgentEscrow.JobStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "jobs"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        jobId: string;
        client: string;
        agent: string;
        token: string;
        amount: bigint;
        status: bigint;
        intentHash: string;
        createdAt: bigint;
        completedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rejectJob"
  ): TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitJob"
  ): TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalJobs"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "JobCompleted"
  ): TypedContractEvent<
    JobCompletedEvent.InputTuple,
    JobCompletedEvent.OutputTuple,
    JobCompletedEvent.OutputObject
  >;
  getEvent(
    key: "JobCreated"
  ): TypedContractEvent<
    JobCreatedEvent.InputTuple,
    JobCreatedEvent.OutputTuple,
    JobCreatedEvent.OutputObject
  >;
  getEvent(
    key: "JobFunded"
  ): TypedContractEvent<
    JobFundedEvent.InputTuple,
    JobFundedEvent.OutputTuple,
    JobFundedEvent.OutputObject
  >;
  getEvent(
    key: "JobRefunded"
  ): TypedContractEvent<
    JobRefundedEvent.InputTuple,
    JobRefundedEvent.OutputTuple,
    JobRefundedEvent.OutputObject
  >;
  getEvent(
    key: "JobRejected"
  ): TypedContractEvent<
    JobRejectedEvent.InputTuple,
    JobRejectedEvent.OutputTuple,
    JobRejectedEvent.OutputObject
  >;
  getEvent(
    key: "JobSubmitted"
  ): TypedContractEvent<
    JobSubmittedEvent.InputTuple,
    JobSubmittedEvent.OutputTuple,
    JobSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "JobCompleted(bytes32,uint256)": TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;
    JobCompleted: TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;

    "JobCreated(bytes32,address,address,address,uint256)": TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;
    JobCreated: TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;

    "JobFunded(bytes32,uint256)": TypedContractEvent<
      JobFundedEvent.InputTuple,
      JobFundedEvent.OutputTuple,
      JobFundedEvent.OutputObject
    >;
    JobFunded: TypedContractEvent<
      JobFundedEvent.InputTuple,
      JobFundedEvent.OutputTuple,
      JobFundedEvent.OutputObject
    >;

    "JobRefunded(bytes32,uint256)": TypedContractEvent<
      JobRefundedEvent.InputTuple,
      JobRefundedEvent.OutputTuple,
      JobRefundedEvent.OutputObject
    >;
    JobRefunded: TypedContractEvent<
      JobRefundedEvent.InputTuple,
      JobRefundedEvent.OutputTuple,
      JobRefundedEvent.OutputObject
    >;

    "JobRejected(bytes32)": TypedContractEvent<
      JobRejectedEvent.InputTuple,
      JobRejectedEvent.OutputTuple,
      JobRejectedEvent.OutputObject
    >;
    JobRejected: TypedContractEvent<
      JobRejectedEvent.InputTuple,
      JobRejectedEvent.OutputTuple,
      JobRejectedEvent.OutputObject
    >;

    "JobSubmitted(bytes32)": TypedContractEvent<
      JobSubmittedEvent.InputTuple,
      JobSubmittedEvent.OutputTuple,
      JobSubmittedEvent.OutputObject
    >;
    JobSubmitted: TypedContractEvent<
      JobSubmittedEvent.InputTuple,
      JobSubmittedEvent.OutputTuple,
      JobSubmittedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
